import React, { useRef, useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PlacesInf from "../src/data/Places";

export default function Home() {
  
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const submitForm = (e) => {
    e.preventDefault();
    console.log(email);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>TEST</div>

      <form>
        {/* <input type="text" placeholder="Nome"></input> */}
        <input type="text" placeholder="Email" onChange={(e)=>setEmail(e.target.value)}></input>
        <input type="text" placeholder="Senha" onChange={(e)=>setPassword(e.target.value)}></input>
        {/* <input type="file" placeholder="Foto"></input> */}
        <input type="submit" onClick={(e) => submitForm(e)}></input>
      </form>

      <div className={styles.a}>INF DE TDS USERS</div>
      <PlacesInf></PlacesInf>
      <div className={styles.a}>INF SENSIVEIS DE CADA USER</div>
    </div>
  );
}
