GET http://localhost:8000/places

################################

POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "7",
    "email": "8",
    "password": "7"
}

################################################################
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
    "email": "1",
    "password": "1"
}

################################################################
GET http://localhost:8000/auth/verifytoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdjMjFlMzI0N2M4MDU4ZGVmY2VkNyIsImlhdCI6MTYzNzcxMTY3NSwiZXhwIjoxNjM3Nzk4MDc1fQ.aCgioCvI9YlkAKQTWTvpxgSbsEEBKwC0NEvyzXD4Tqw

#########################################
POST http://localhost:8000/auth/forgot_password
Content-Type: application/json

{
    "email": "lucasdafonsecadepaula@gmail.com"
}

#########################################
POST http://localhost:8000/auth/forgot_password_verify_token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWQ4OGU2MjUyNzFmNWM2NDMxNzYzOCIsImlhdCI6MTYzNzgwMTk2NSwiZXhwIjoxNjM3ODAyODY1fQ.Crz-vUt9sxtzd-8JV-0OA7hVPYGxqucjvnY2dA8cSlo",
    "password": "555"
}