GET http://localhost:8000/places

################################

POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "5",
    "email": "5",
    "password": "5"
}

################################################################
POST http://localhost:8000/auth/authenticate
Content-Type: application/json

{
    "email": "1",
    "password": "1"
}

################################################################
GET http://localhost:8000/auth/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTdhNzdkMzI0N2M4MDU4ZGVmY2UxMSIsImlhdCI6MTYzNzMzMzE5OSwiZXhwIjoxNjM3NDE5NTk5fQ.77GcByoDSSp7cyIxqi5VKazMEuTyV7iKClCUsth3L9k