GET http://localhost:8000/

################################

POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "Lucas222",
    "email": "3622222",
    "password": "123"
}

################################################################
POST http://localhost:8000/auth/authenticate
Content-Type: application/json

{
    "email": "3622222",
    "password": "123"
}

################################################################
GET http://localhost:8000/auth/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTA0YWIzNDczMDA0ODg4M2JjOTVmYiIsImlhdCI6MTYzNjg0NjYxMSwiZXhwIjoxNjM2OTMzMDExfQ.vJEe6v4nFRmrVdFThQShIXsSBTLWM8xeYoQGBOTjPf0